name: Deployment exercise 1

on:
    push:
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint

    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 20
            - name: Install dependencies
              run: npm ci
            - name: Test
              run: npm run test

    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            
            - name: Install dependencies
              run: npm ci
            
            - name: Build Project
              run: npm run build
            
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME || 'default-username' }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Build Docker Image
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .
            
            - name: Push Docker Image to Docker Hub
              run: |
                docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
            
            - name: Deploy Project
              run: echo "Application deployed via Docker Hub"

    execute:
        needs: deploy
        runs-on: ubuntu-latest
        steps:
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Pull Docker Image
              run: |
                docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
            
            - name: Run Docker Container
              run: |
                docker run -d -p 3000:80 --name my-running-app ${{ secrets.DOCKER_USERNAME }}/my-app:latest
